export const ClubOptions = [
    'A.C.E Unity Club', 
    'Active Minds Club', 
    'American Sign Language Club', 
    'Anthropology Club', 
    'Business Club',
    'Computer Science Club',
    'Cheer Club',
    'Entrepreneur Club',
    'Electronic Music Club',
    'Freedom Forum',
    'Film Club', 
    'Geology Club',
    'Great Valley Astronomy Club',
    'International Club',
    'Intervarsity Christian Fellowship',
    'MANRRS Club',
    'Math and Engineering Club',
    'Musicians Guild',
    'Parrots Club',
    'Pre-Health Club',
    'Respiratory Care Club',
    'Science Club',
    'Sports Medicine Club',
    'Video Game Development Club',
    'Visual Arts Club',
    'Young Farmers',
  ];